// Generated by gencpp from file rt1_pkg/LastTargetResponse.msg
// DO NOT EDIT!


#ifndef RT1_PKG_MESSAGE_LASTTARGETRESPONSE_H
#define RT1_PKG_MESSAGE_LASTTARGETRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rt1_pkg
{
template <class ContainerAllocator>
struct LastTargetResponse_
{
  typedef LastTargetResponse_<ContainerAllocator> Type;

  LastTargetResponse_()
    : x(0.0)
    , y(0.0)  {
    }
  LastTargetResponse_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::rt1_pkg::LastTargetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rt1_pkg::LastTargetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LastTargetResponse_

typedef ::rt1_pkg::LastTargetResponse_<std::allocator<void> > LastTargetResponse;

typedef boost::shared_ptr< ::rt1_pkg::LastTargetResponse > LastTargetResponsePtr;
typedef boost::shared_ptr< ::rt1_pkg::LastTargetResponse const> LastTargetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rt1_pkg::LastTargetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rt1_pkg::LastTargetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rt1_pkg::LastTargetResponse_<ContainerAllocator1> & lhs, const ::rt1_pkg::LastTargetResponse_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rt1_pkg::LastTargetResponse_<ContainerAllocator1> & lhs, const ::rt1_pkg::LastTargetResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rt1_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rt1_pkg::LastTargetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rt1_pkg::LastTargetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rt1_pkg::LastTargetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rt1_pkg::LastTargetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt1_pkg::LastTargetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt1_pkg::LastTargetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rt1_pkg::LastTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff8d7d66dd3e4b731ef14a45d38888b6";
  }

  static const char* value(const ::rt1_pkg::LastTargetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff8d7d66dd3e4b73ULL;
  static const uint64_t static_value2 = 0x1ef14a45d38888b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::rt1_pkg::LastTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rt1_pkg/LastTargetResponse";
  }

  static const char* value(const ::rt1_pkg::LastTargetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rt1_pkg::LastTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response part\n"
"float32 x\n"
"float32 y\n"
"\n"
;
  }

  static const char* value(const ::rt1_pkg::LastTargetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rt1_pkg::LastTargetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LastTargetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rt1_pkg::LastTargetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rt1_pkg::LastTargetResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RT1_PKG_MESSAGE_LASTTARGETRESPONSE_H
