// Generated by gencpp from file rt1_pkg/LastTargetRequest.msg
// DO NOT EDIT!


#ifndef RT1_PKG_MESSAGE_LASTTARGETREQUEST_H
#define RT1_PKG_MESSAGE_LASTTARGETREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rt1_pkg
{
template <class ContainerAllocator>
struct LastTargetRequest_
{
  typedef LastTargetRequest_<ContainerAllocator> Type;

  LastTargetRequest_()
    {
    }
  LastTargetRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::rt1_pkg::LastTargetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rt1_pkg::LastTargetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LastTargetRequest_

typedef ::rt1_pkg::LastTargetRequest_<std::allocator<void> > LastTargetRequest;

typedef boost::shared_ptr< ::rt1_pkg::LastTargetRequest > LastTargetRequestPtr;
typedef boost::shared_ptr< ::rt1_pkg::LastTargetRequest const> LastTargetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rt1_pkg::LastTargetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rt1_pkg::LastTargetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace rt1_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rt1_pkg::LastTargetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rt1_pkg::LastTargetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rt1_pkg::LastTargetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rt1_pkg::LastTargetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt1_pkg::LastTargetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt1_pkg::LastTargetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rt1_pkg::LastTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rt1_pkg::LastTargetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rt1_pkg::LastTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rt1_pkg/LastTargetRequest";
  }

  static const char* value(const ::rt1_pkg::LastTargetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rt1_pkg::LastTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request part (empty)\n"
;
  }

  static const char* value(const ::rt1_pkg::LastTargetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rt1_pkg::LastTargetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LastTargetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rt1_pkg::LastTargetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rt1_pkg::LastTargetRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // RT1_PKG_MESSAGE_LASTTARGETREQUEST_H
