// Generated by gencpp from file rt1_pkg/RobotPosVel.msg
// DO NOT EDIT!


#ifndef RT1_PKG_MESSAGE_ROBOTPOSVEL_H
#define RT1_PKG_MESSAGE_ROBOTPOSVEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rt1_pkg
{
template <class ContainerAllocator>
struct RobotPosVel_
{
  typedef RobotPosVel_<ContainerAllocator> Type;

  RobotPosVel_()
    : x(0.0)
    , y(0.0)
    , vx(0.0)
    , vy(0.0)  {
    }
  RobotPosVel_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , vx(0.0)
    , vy(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _vx_type;
  _vx_type vx;

   typedef float _vy_type;
  _vy_type vy;





  typedef boost::shared_ptr< ::rt1_pkg::RobotPosVel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rt1_pkg::RobotPosVel_<ContainerAllocator> const> ConstPtr;

}; // struct RobotPosVel_

typedef ::rt1_pkg::RobotPosVel_<std::allocator<void> > RobotPosVel;

typedef boost::shared_ptr< ::rt1_pkg::RobotPosVel > RobotPosVelPtr;
typedef boost::shared_ptr< ::rt1_pkg::RobotPosVel const> RobotPosVelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rt1_pkg::RobotPosVel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rt1_pkg::RobotPosVel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rt1_pkg::RobotPosVel_<ContainerAllocator1> & lhs, const ::rt1_pkg::RobotPosVel_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.vx == rhs.vx &&
    lhs.vy == rhs.vy;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rt1_pkg::RobotPosVel_<ContainerAllocator1> & lhs, const ::rt1_pkg::RobotPosVel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rt1_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rt1_pkg::RobotPosVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rt1_pkg::RobotPosVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rt1_pkg::RobotPosVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rt1_pkg::RobotPosVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt1_pkg::RobotPosVel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt1_pkg::RobotPosVel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rt1_pkg::RobotPosVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2af08925b9da4c99c24669eae33385e8";
  }

  static const char* value(const ::rt1_pkg::RobotPosVel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2af08925b9da4c99ULL;
  static const uint64_t static_value2 = 0xc24669eae33385e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::rt1_pkg::RobotPosVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rt1_pkg/RobotPosVel";
  }

  static const char* value(const ::rt1_pkg::RobotPosVel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rt1_pkg::RobotPosVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Position\n"
"float32 x\n"
"float32 y\n"
"#Velocity\n"
"float32 vx\n"
"float32 vy\n"
;
  }

  static const char* value(const ::rt1_pkg::RobotPosVel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rt1_pkg::RobotPosVel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.vx);
      stream.next(m.vy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotPosVel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rt1_pkg::RobotPosVel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rt1_pkg::RobotPosVel_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "vx: ";
    Printer<float>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<float>::stream(s, indent + "  ", v.vy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RT1_PKG_MESSAGE_ROBOTPOSVEL_H
