// Generated by gencpp from file rt1_pkg/RobotToTarget.msg
// DO NOT EDIT!


#ifndef RT1_PKG_MESSAGE_ROBOTTOTARGET_H
#define RT1_PKG_MESSAGE_ROBOTTOTARGET_H

#include <ros/service_traits.h>


#include <rt1_pkg/RobotToTargetRequest.h>
#include <rt1_pkg/RobotToTargetResponse.h>


namespace rt1_pkg
{

struct RobotToTarget
{

typedef RobotToTargetRequest Request;
typedef RobotToTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotToTarget
} // namespace rt1_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rt1_pkg::RobotToTarget > {
  static const char* value()
  {
    return "185aad6ed636881de3d9111fc76b7e00";
  }

  static const char* value(const ::rt1_pkg::RobotToTarget&) { return value(); }
};

template<>
struct DataType< ::rt1_pkg::RobotToTarget > {
  static const char* value()
  {
    return "rt1_pkg/RobotToTarget";
  }

  static const char* value(const ::rt1_pkg::RobotToTarget&) { return value(); }
};


// service_traits::MD5Sum< ::rt1_pkg::RobotToTargetRequest> should match
// service_traits::MD5Sum< ::rt1_pkg::RobotToTarget >
template<>
struct MD5Sum< ::rt1_pkg::RobotToTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rt1_pkg::RobotToTarget >::value();
  }
  static const char* value(const ::rt1_pkg::RobotToTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rt1_pkg::RobotToTargetRequest> should match
// service_traits::DataType< ::rt1_pkg::RobotToTarget >
template<>
struct DataType< ::rt1_pkg::RobotToTargetRequest>
{
  static const char* value()
  {
    return DataType< ::rt1_pkg::RobotToTarget >::value();
  }
  static const char* value(const ::rt1_pkg::RobotToTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rt1_pkg::RobotToTargetResponse> should match
// service_traits::MD5Sum< ::rt1_pkg::RobotToTarget >
template<>
struct MD5Sum< ::rt1_pkg::RobotToTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rt1_pkg::RobotToTarget >::value();
  }
  static const char* value(const ::rt1_pkg::RobotToTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rt1_pkg::RobotToTargetResponse> should match
// service_traits::DataType< ::rt1_pkg::RobotToTarget >
template<>
struct DataType< ::rt1_pkg::RobotToTargetResponse>
{
  static const char* value()
  {
    return DataType< ::rt1_pkg::RobotToTarget >::value();
  }
  static const char* value(const ::rt1_pkg::RobotToTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RT1_PKG_MESSAGE_ROBOTTOTARGET_H
