(cl:defpackage rt1_pkg-srv
  (:use )
  (:export
   "LASTTARGET"
   "<LASTTARGET-REQUEST>"
   "LASTTARGET-REQUEST"
   "<LASTTARGET-RESPONSE>"
   "LASTTARGET-RESPONSE"
   "ROBOTTOTARGET"
   "<ROBOTTOTARGET-REQUEST>"
   "ROBOTTOTARGET-REQUEST"
   "<ROBOTTOTARGET-RESPONSE>"
   "ROBOTTOTARGET-RESPONSE"
  ))

